name: build

on: ["push", "pull_request"]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: "3.8"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install flake8==5.0.4 mypy==0.971 mypy-extensions==0.4.3 types-python-dateutil==2.8.19 types-requests==2.28.10 typing_extensions==4.3.0 coverage==6.4.4
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Static type checking with mypy
      run: |
        python -m mypy --strict .
    - name: Unit tests
      run: |
        python -m unittest -v
    - name: Generate code coverage reports
      run: |
        python -m coverage run test/test_api.py -v
        python -m coverage lcov -o ./coverage/lcov.info
        python -m coverage report
